project:
  type: website
  output-dir: docs 

website:
  repo-url: https://github.com/sahana-alt/blogsml1
  title: "Blogs ML1"
  repo-actions: [source]
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



